import importlib.util
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


ROOT = Path(__file__).resolve().parents[1]
MODULE = ROOT / "services/manager-web/metadata_store.py"


def load(**env):
    clean_env = os.environ.copy()
    clean_env.pop("METADATA_DB_BACKEND", None)
    clean_env.pop("METADATA_DATABASE_URL", None)
    clean_env.update(env)
    with patch.dict(os.environ, clean_env, clear=True):
        spec = importlib.util.spec_from_file_location("metadata_store_test", MODULE)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    return module


class MetadataBackendConfigTests(unittest.TestCase):
    def test_sqlite_remains_default(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            module = load(METADATA_DB_FILE=str(Path(temp_dir) / "manager.db"))
            module.initialize(schema_file=ROOT / "db/schema.sql")
            with module.connect() as conn:
                self.assertEqual(conn.execute("SELECT 1").fetchone()[0], 1)

    def test_sqlite_readonly_connection_does_not_create_database(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            database = Path(temp_dir) / "missing.db"
            module = load(METADATA_DB_FILE=str(database))
            with self.assertRaises(module.DATABASE_ERROR):
                with module.connect(readonly=True):
                    pass
            self.assertFalse(database.exists())

    def test_postgres_connection_requires_url(self):
        module = load(METADATA_DB_BACKEND="postgres")
        with self.assertRaisesRegex(RuntimeError, "METADATA_DATABASE_URL"):
            with module.connect():
                pass

    def test_postgres_connection_requires_driver(self):
        module = load(
            METADATA_DB_BACKEND="postgres",
            METADATA_DATABASE_URL="postgresql://unused",
        )
        with patch.object(module, "psycopg", None):
            with self.assertRaisesRegex(RuntimeError, "psycopg"):
                with module.connect():
                    pass

    def test_postgres_wrapper_translates_queries_and_rows(self):
        module = load()

        class Cursor:
            description = [type("Column", (), {"name": "id"})()]
            rowcount = 1

            def fetchone(self):
                return (7,)

        class Connection:
            def __init__(self):
                self.calls = []

            def execute(self, sql, params=(), **kwargs):
                self.calls.append((sql, params, kwargs))
                return Cursor()

        raw = Connection()
        conn = module._PostgresConnection(raw)
        row = conn.execute("SELECT id FROM users WHERE public_id = ?", ("u",)).fetchone()
        self.assertEqual(raw.calls[-1][0], "SELECT id FROM users WHERE public_id = %s")
        self.assertEqual(row[0], 7)
        self.assertEqual(row["id"], 7)
        conn.execute("SELECT last_insert_rowid()")
        self.assertEqual(raw.calls[-1][0], "SELECT LASTVAL()")

    def test_postgres_row_keeps_duplicate_columns_for_positional_access(self):
        row = load()._CompatRow(("id", "id"), (7, 9))
        self.assertEqual((row[0], row[1], row["id"]), (7, 9, 9))

    def test_postgres_write_uses_transaction_lock(self):
        module = load()

        class Connection:
            def __init__(self):
                self.sql = []

            def execute(self, sql):
                self.sql.append(sql)

        connection = Connection()
        with patch.object(module, "DB_BACKEND", "postgres"):
            module.begin_write(connection)
        self.assertEqual(connection.sql, ["SELECT pg_advisory_xact_lock(684626972)"])

    def test_postgres_schema_has_no_sqlite_only_syntax(self):
        schema = (ROOT / "db/schema.postgres.sql").read_text(encoding="utf-8")
        for token in ("PRAGMA", "AUTOINCREMENT", "INSERT OR IGNORE", "datetime('now')"):
            with self.subTest(token=token):
                self.assertNotIn(token, schema)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", schema)
        self.assertIn("prevent_instance_owner_member_insert", schema)
        self.assertEqual(schema.count("$$"), 4)

    def test_queries_do_not_qualify_postgres_current_user_keyword(self):
        source = MODULE.read_text(encoding="utf-8")
        self.assertNotIn("current_user.", source)


if __name__ == "__main__":
    unittest.main()
